language: node_js
node_js:
- node
sudo: false
cache: npm
before_install:
- npm install gulp -g
script:
- npm install
env:
  global:
  - secure: HIobY8ozJM9yVFcG+ufO65gkA7jOsUgQ7r1bc3Pgf/wZayS71gO9jJFMmSmfUoQGDbSbDnyUmZWtRmEYnKZS2fSfirfCy2b9jznYzryl4mBKHrJaCdKjZOjshYHju4bMW4PN171dm9FRz/iMQj39mooCdJxxSfQHP0Wm8rVPXoOlOUs+V6BRBdba6frrx3fsf/qGO/A5ejezS1mfA0qDL8kiJlD7zYmPNVdtPIILbOKX5VwUL5JOq0CkWZD4BpUpDi1I2eNL1Gr8DZbNune+EKVr9gnwTgkprBuwtFpBEzUl0fJuVBsIe1A9qY0BchY/ZcnXAvNNb+DHH+hF2So1SR3MXcijgYKUs8ASubdiacJXU47tar3wHpzzNEj1+F51ghDGOUpvkma1VGDou1KB2s/uWTDmHhwBQ4y+F8tTqd6Fs/Pv43M5FGICJLcRPhNYNLgBc30+56Q4S9aVib0/9osaUfzFiUKomDHO5Uw61NKaWs0jh96yhRo3aoO0VB25MWlq9t1rV4An7kokzJpmA6FZsbj+hVy5ZIzGLr1cG5vvxyJGvHyAiUDajvJvkf3eZ9lMq5EC/nMMrZHlL5frSy9KLeSiSAo7eHMK7xD8+s59CZEaTV219rIR93OPfuyse+sKFGXw8zxSKwFYARBlW+eV5pMWoasRNxBEMXMnB3I=
  - secure: gBMbFtOHRjhYItQI9+crI4NXn8uYpVMX10nr/3BxJrjEbb4WjoTQPMbBXySYB2Sj8M0hiLxZfaUcxVV46Hn2FiSe3p2DnJ3ONeGxvOykwxpNy6DAkW39C9/gMmsn0lGaDk5gwZ4P0UB7wu3PlOzPZEq2v8/InHGq2fyh5NvIsi12f6GlRsv13FRLSWJYN2M2qLIl1b2kYzxEpqEeLjenxbBqArJWhCdqyISfct2031YtYZ5KJ/CPHMY8sQKOg/SCMZrpTxnEZAyigv/5oPDt1JshxOj55i4kHVaUB1svIMrNgWWuw78HnD4N6CaFMiWDUOQwfWfHWEojWPJ+VOyWqUb4UCJGp0JYiTnZX1ebkZDeTU2AkSrkEq0IwOb+2dc2k48PMLSm25MEnn6izNveTmnokzXthpN5CIJqU3YMuao0EoCNco+3W95Dn3OWMesPl/UbyeGnixBL+UUyJ37tfafv3Z//kaNWTb8EK3WUYvDrfTJggIF2WfN6VCHff1oq1uEvQfeWcNctD2f0jLE6coMDyQInniys8BWIY5ROOYd0jY7SIwVeP9pyZwRgV1INUEjqgZuzwb1lE4pSi9LUxuyCVV5Phx0OAb2Pk3CoWOf/oMFJ8I7kWinIa2wzQIbLOqKetGCaxUohovB9uYJ7tnurBmrFJkLc20NV5KYGDaM=
deploy:
  provider: script
  skip_cleanup: true
  script: echo "user $FTP_USER password $FTP_PASSWORD"
  # script: gulp deploy --user $FTP_USER --password $FTP_PASSWORD
  on:
    branch: master
