language: node_js
node_js:
- node
sudo: false
cache: npm
before_install:
- npm install gulp -g
script:
- npm install
env:
  global:
  - secure: PlFdJG1qov7QlWY4IwqzdIc3ftvsXmfrearEJuSH5gyDYpQxZ6fpXAUvZBOVf4y4iyoCpg8fLEtq3gyiAtKiRbeKCYeFXvZlpW+lOEg+QQKv5cuKXLK+Nk3zcRyLdwXKkDf+2KoLYWqFThTlmOy8PBxR1EgcFA88GvRziTCgDdv7qpg4XNS4ZNlxWJKBsyLFdNk+nXTubH2YOas34GkD+bsRlhmsSCRaCkais+kbabiA1zpda6wNL+LFTExJOnvgI4R9R3xFmAHbtiTSpQpmkGsUp5Z5RhzsXQdvCvfHomrNkKTHQCOYpxGV2IIECxwYWNGhVEuwBGzJDFGAeztBUKLTH/qWAloh/tS/Ps9weWZq809e6gp2gBgKywfT1yLBfXV3pmJ3xUEjS2YNYBzQUaj0uEf6sbJqHUKu7VikfgE8lXLF8ZFSseRAQxtp9SA5H9Ic5LprFRs/WLpJNnlzXxuI7mHp90eSDveJUutckugh5zwUiBvceBdQTlk2d95Ac9y1lupqrh8gQ48UKcZTQ2HCarxxF5g+jaOW5Tb0MBpcm4CYt+59btuHUsKDPy/Cy1C7qUdq2UQkwF8eBq6Uis5NJw0eOaUFR4zYAfWzDSMlgn/2P3j1DABjAnkWwY5/3gJH1wD6CFGQi+q5I8kU0DD8Gm7LB8GIOK9erGqVWZ8=
  - secure: P6P/TJLEMGTeennRMHLmFClhoJ7p8JDD25I/jLxbuhVXlGuX2y41GO0a+u6vBSgx1AZsdpgFk9miRMpuwiwWE0TN7s2yPO9rkL7GYL4b61SBRcwYcW6hxYADF6JgCENB4Jav2aCsG6p7GUjfbUxpzKZKfNMvP+B6TSnsvVfIrGOwkqqfRGvzwm4DSo6jYuJW7KzIt0FOo7vftL77Lq3zuNw7caXie5FyHChRhyY6SXGZDcyqCGL7JcvF2neu2VzxB75KOP3yLzFpMhkrDxvBRIybwzIYPhLyoKafQWxF/sx3eU4kb0gPVtve8aP5CbDt+854CqOACxrmOfmHXihcs3RdZn+8wM8WicWP1K8Nvlz8vi4M+nvpH4SvwCdPYBJ/h9YYA4HdrA4bgL/zDF8p8YAMNfc6OYsp3bRiLvoKnew35Dle7DK/3yj4iO/K6xyeKF3v0az05Giyulgag+BhDgbD/6kflxR+xAsOWV/t2OqtEWNyadoSy1mQm8MgRNwcBM3cVXI3JA9Tsla+KS8XVPXXDa4UkwWtFPBvUp44Wb1k11YmMCVGU1DFGgFvCSrEXrl6cE/fIjGAIejIuWBQC3w/OE/mA9qWRn3oaGQjm6D5DQULjmcdSPbaAOQHnRYrpnjkG3qAvVEv37HDf0d6zv0bdk36xMdaqtbf98QEiOc=
deploy:
  provider: script
  skip_cleanup: true
  script: gulp deploy --user $FTP_USER --password $FTP_PASSWORD
  on:
    branch: master
